name: Compile LaTeX

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper.tex

      - name: Commit and push updated paper.pdf (if changed)
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 변경 사항 스테이징
          git add paper.pdf

          # 변경이 있을 경우만 커밋 & 푸시
          if git diff --staged --quiet; then
            echo "No changes to paper.pdf — nothing to commit."
          else
            git commit -m "ci: update compiled paper.pdf"
            git push origin HEAD:main
            echo "Updated paper.pdf pushed to main."
          fi
